"""
Navigational Hazard Alert and Rule-Based Advisory Service for Antarctic Waters.

NOTICE: All generated advisories are automated, illustrative scenario alerts computed
from environmental rules and active tracking data. They are NOT official NAVAREA, WMO,
or government hydrographic office bulletins.
"""
from __future__ import annotations

import logging
import math
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from ..data.ingestion import environmental_data_provider
from .iceberg_service import iceberg_service

logger = logging.getLogger(__name__)

DISCLAIMER_TEXT = (
    "Illustrative scenario alert generated by POLARIS rule engine; "
    "not an official NAVAREA/WMO bulletin."
)


def _haversine_nm(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Computes great-circle distance in nautical miles between two coordinates."""
    r_nm = 3440.065
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = (math.sin(dphi / 2.0) ** 2 +
         math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2.0) ** 2)
    return 2.0 * r_nm * math.atan2(math.sqrt(a), math.sqrt(max(0.0, 1.0 - a)))


class AlertService:
    """Rule-triggered polar navigational advisory generator."""

    def __init__(self):
        self._cached_alerts: List[Dict[str, Any]] = []
        self._last_refresh: float = 0.0

    def list_alerts(self, force_refresh: bool = False) -> List[Dict[str, Any]]:
        """
        Generates active rule-triggered polar hazard alerts.
        Advisories are triggered by physical thresholds (winds, icebergs, fast-ice).
        is_live is set strictly by whether live telemetry was successfully fetched.
        """
        now = time.time()
        if not force_refresh and self._cached_alerts and (now - self._last_refresh < 30.0):
            return self._cached_alerts

        now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        alerts: List[Dict[str, Any]] = []

        # ------------------------------------------------------------------- #
        # Rule 1: Katabatic / Synoptic Wind Alert (Maitri / Queen Maud Land)
        # ------------------------------------------------------------------- #
        maitri_lat, maitri_lon = -70.767, 11.733
        try:
            w_maitri = environmental_data_provider.get_live_weather(
                maitri_lat, maitri_lon, timeout_s=2.5
            )
            m_is_live = bool(w_maitri.get("is_live", False))
            m_temp = w_maitri.get("temperature_2m_c")
            m_wind = w_maitri.get("wind_speed_knots")
            m_source = w_maitri.get("data_source", "Offline Metocean Store")
        except Exception as e:
            logger.warning("Failed to fetch weather for Maitri alert: %s", e)
            m_is_live = False
            m_temp = None
            m_wind = None
            m_source = "Offline Metocean Store (error fallback)"

        # Threshold evaluation
        wind_val = m_wind if m_wind is not None else 20.0
        temp_val = m_temp if m_temp is not None else -15.0
        if wind_val >= 34.0:
            severity = "CRITICAL"
            lead_desc = f"Katabatic gale force conditions detected ({wind_val:.1f} kts)."
        elif wind_val >= 22.0:
            severity = "WARNING"
            lead_desc = f"Elevated wind conditions observed ({wind_val:.1f} kts)."
        else:
            severity = "INFO"
            lead_desc = f"Moderate wind conditions observed ({wind_val:.1f} kts)."

        feed_tag = "Live metocean feed" if m_is_live else "Offline metocean reference store"
        temp_str = f"{temp_val:.1f}°C" if m_temp is not None else "N/A"

        alerts.append({
            "id": "ALERT-POLARIS-WIND-MAITRI",
            "timestamp": now_iso,
            "severity": severity,
            "source": "POLARIS Rule Engine (illustrative scenario alert, not an official bulletin)",
            "is_official_bulletin": False,
            "disclaimer": DISCLAIMER_TEXT,
            "title": f"WIND ADVISORY: MAITRI / QUEEN MAUD LAND ({severity})",
            "description": (
                f"Continental slope off Maitri Station (70°46'S, 11°44'E). {feed_tag}: "
                f"Temp {temp_str}, Wind {wind_val:.1f} kts (Source: {m_source}). "
                f"{lead_desc} Rapid sea-ice compaction potential along ice shelf barrier."
            ),
            "coordinates": {"lat": maitri_lat, "lon": maitri_lon},
            "recommended_action": (
                "Avoid entering dense pack within 40 NM of coast during peak wind windows. "
                "Maintain continuous radar watch for compression ridging."
            ),
            "is_live": m_is_live,
            "trigger_metrics": {
                "wind_speed_knots": m_wind,
                "temperature_c": m_temp,
                "data_source": m_source,
            }
        })

        # ------------------------------------------------------------------- #
        # Rule 2: Fast-Ice & Approach Advisory (Bharati / Prydz Bay Sector)
        # ------------------------------------------------------------------- #
        bharati_lat, bharati_lon = -69.407, 76.187
        try:
            w_bharati = environmental_data_provider.get_live_weather(
                bharati_lat, bharati_lon, timeout_s=2.5
            )
            b_is_live = bool(w_bharati.get("is_live", False))
            b_temp = w_bharati.get("temperature_2m_c")
            b_wind = w_bharati.get("wind_speed_knots")
            b_source = w_bharati.get("data_source", "Offline Metocean Store")
        except Exception as e:
            logger.warning("Failed to fetch weather for Bharati alert: %s", e)
            b_is_live = False
            b_temp = None
            b_wind = None
            b_source = "Offline Metocean Store (error fallback)"

        b_wind_val = b_wind if b_wind is not None else 18.0
        b_temp_val = b_temp if b_temp is not None else -12.0
        b_feed_tag = "Live metocean feed" if b_is_live else "Offline metocean reference store"
        b_temp_str = f"{b_temp_val:.1f}°C" if b_temp is not None else "N/A"

        alerts.append({
            "id": "ALERT-POLARIS-APPROACH-BHARATI",
            "timestamp": now_iso,
            "severity": "HIGH",
            "source": "POLARIS Rule Engine (illustrative scenario alert, not an official bulletin)",
            "is_official_bulletin": False,
            "disclaimer": DISCLAIMER_TEXT,
            "title": "FAST-ICE REGIME & APPROACH ADVISORY: BHARATI SECTOR",
            "description": (
                f"Prydz Bay approach (69°24'S, 76°11'E). {b_feed_tag}: "
                f"Temp {b_temp_str}, Wind {b_wind_val:.1f} kts (Source: {b_source}). "
                "Fast-ice fracture front and coastal pressure ridging active in approach corridor."
            ),
            "coordinates": {"lat": bharati_lat, "lon": bharati_lon},
            "recommended_action": (
                "Vessels without Polar Class PC4 or higher require ice reconnaissance "
                "helicopter scouting before final approach to fast-ice edge."
            ),
            "is_live": b_is_live,
            "trigger_metrics": {
                "wind_speed_knots": b_wind,
                "temperature_c": b_temp,
                "data_source": b_source,
            }
        })

        # ------------------------------------------------------------------- #
        # Rule 3: Iceberg Tracking & Drift Corridor Advisory
        # ------------------------------------------------------------------- #
        all_bergs = iceberg_service.list_icebergs()
        # Find any live-tracked iceberg first; fallback to largest archived berg
        live_bergs = [b for b in all_bergs if b.get("is_live")]
        if live_bergs:
            target_berg = live_bergs[0]
            berg_is_live = True
            tracking_note = (
                f"Live satellite scatterometer fix (DOY {target_berg.get('observation_doy', 'N/A')}, "
                f"Source: {target_berg.get('surveillance_source', 'BYU/ASCAT')})."
            )
        else:
            # Check for A-23a or highest-area archived berg
            target_berg = next((b for b in all_bergs if b.get("id") == "A-23a"), None)
            if not target_berg and all_bergs:
                target_berg = max(all_bergs, key=lambda b: b.get("area_km2") or 0.0)
            berg_is_live = False
            tracking_note = (
                "Historical BYU/USNIC consolidated archive fix. "
                "Note: A-23a is not currently listed on the active BYU near-real-time scatterometer feed."
            )

        if target_berg:
            b_lat = float(target_berg["lat"])
            b_lon = float(target_berg["lon"])
            area_val = target_berg.get("area_km2")
            area_str = f"{area_val:,.0f} km²" if area_val is not None else "Dimension unmeasured"

            alerts.append({
                "id": f"ALERT-POLARIS-BERG-{target_berg['id']}",
                "timestamp": now_iso,
                "severity": "CRITICAL" if b_lat > -63.0 else "WARNING",
                "source": "POLARIS Rule Engine (illustrative scenario alert, not an official bulletin)",
                "is_official_bulletin": False,
                "disclaimer": DISCLAIMER_TEXT,
                "title": f"TABULAR ICEBERG ADVISORY: {target_berg['name'].upper()}",
                "description": (
                    f"Iceberg {target_berg['id']} ({area_str}) located at "
                    f"{abs(b_lat):.2f}°{'S' if b_lat < 0 else 'N'}, "
                    f"{abs(b_lon):.2f}°{'W' if b_lon < 0 else 'E'}. "
                    f"{tracking_note} Calved growlers and bergy bits possible within 30 NM radius."
                ),
                "coordinates": {"lat": b_lat, "lon": b_lon},
                "recommended_action": (
                    "Maintain minimum 30 NM stand-off; keep continuous forward radar watch "
                    "and searchlight readiness in poor visibility."
                ),
                "is_live": berg_is_live,
                "trigger_metrics": {
                    "iceberg_id": target_berg["id"],
                    "lat": b_lat,
                    "lon": b_lon,
                    "area_km2": area_val,
                    "is_live_track": berg_is_live
                }
            })

        self._cached_alerts = alerts
        self._last_refresh = now
        return alerts


alert_service = AlertService()
