"""
Navigational Hazard Alert and Rule-Based Advisory Service for Antarctic Waters.

NOTICE: All generated advisories are automated, illustrative scenario alerts computed
from environmental rules and active tracking data. They are NOT official NAVAREA, WMO,
or government hydrographic office bulletins.
"""
from __future__ import annotations

import logging
import math
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from ..data.ingestion import environmental_data_provider
from .iceberg_service import iceberg_service
from .vessel_service import vessel_service

logger = logging.getLogger(__name__)

DISCLAIMER_TEXT = (
    "Illustrative scenario alert generated by POLARIS rule engine; "
    "not an official NAVAREA/WMO bulletin."
)


def _haversine_nm(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Computes great-circle distance in nautical miles between two coordinates."""
    r_nm = 3440.065
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = (math.sin(dphi / 2.0) ** 2 +
         math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2.0) ** 2)
    return 2.0 * r_nm * math.atan2(math.sqrt(a), math.sqrt(max(0.0, 1.0 - a)))


class AlertService:
    """Rule-triggered polar navigational advisory generator."""

    def __init__(self):
        self._cached_alerts: List[Dict[str, Any]] = []
        self._last_refresh: float = 0.0

    def list_alerts(self, force_refresh: bool = False) -> List[Dict[str, Any]]:
        """
        Generates active rule-triggered polar hazard alerts.
        Advisories are triggered by physical thresholds (winds, icebergs, fast-ice).
        is_live is set strictly by whether live telemetry was successfully fetched.
        """
        now = time.time()
        if not force_refresh and self._cached_alerts and (now - self._last_refresh < 30.0):
            return self._cached_alerts

        now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        alerts: List[Dict[str, Any]] = []

        # ------------------------------------------------------------------- #
        # Rule 1: Katabatic / Synoptic Wind Alert (Maitri / Queen Maud Land)
        # ------------------------------------------------------------------- #
        maitri_lat, maitri_lon = -70.767, 11.733
        try:
            w_maitri = environmental_data_provider.get_live_weather(
                maitri_lat, maitri_lon, timeout_s=2.5
            )
            m_is_live = bool(w_maitri.get("is_live", False))
            m_temp = w_maitri.get("temperature_2m_c")
            m_wind = w_maitri.get("wind_speed_knots")
            m_source = w_maitri.get("data_source", "Offline Metocean Store")
        except Exception as e:
            logger.warning("Failed to fetch weather for Maitri alert: %s", e)
            m_is_live = False
            m_temp = None
            m_wind = None
            m_source = "Offline Metocean Store (error fallback)"

        # Physical threshold evaluation: fire ONLY if wind speed meets warning/critical thresholds
        # Do NOT invent default numerical constants (no 20.0 kts or -15.0°C)
        if m_wind is not None and m_wind >= 22.0:
            if m_wind >= 34.0:
                m_severity = "CRITICAL"
                m_lead = f"Katabatic gale force conditions detected ({m_wind:.1f} kts)."
            else:
                m_severity = "WARNING"
                m_lead = f"Elevated wind conditions observed ({m_wind:.1f} kts)."

            feed_tag = "Live metocean feed" if m_is_live else "Offline metocean reference store"
            temp_str = f"{m_temp:.1f}°C" if m_temp is not None else "no data"
            wind_str = f"{m_wind:.1f} kts" if m_wind is not None else "no data"

            alerts.append({
                "id": "ALERT-POLARIS-WIND-MAITRI",
                "timestamp": now_iso,
                "severity": m_severity,
                "source": "POLARIS Rule Engine (illustrative scenario alert, not an official bulletin)",
                "is_official_bulletin": False,
                "disclaimer": DISCLAIMER_TEXT,
                "title": f"WIND ADVISORY: MAITRI / QUEEN MAUD LAND ({m_severity})",
                "description": (
                    f"Continental slope off Maitri Station (70°46'S, 11°44'E). {feed_tag}: "
                    f"Temp {temp_str}, Wind {wind_str} (Source: {m_source}). "
                    f"{m_lead} Rapid sea-ice compaction potential along ice shelf barrier."
                ),
                "coordinates": {"lat": maitri_lat, "lon": maitri_lon},
                "recommended_action": (
                    "Avoid entering dense pack within 40 NM of coast during peak wind windows. "
                    "Maintain continuous radar watch for compression ridging."
                ),
                "is_live": m_is_live,
                "trigger_metrics": {
                    "wind_speed_knots": m_wind if m_wind is not None else "no data",
                    "temperature_c": m_temp if m_temp is not None else "no data",
                    "data_source": m_source,
                }
            })

        # ------------------------------------------------------------------- #
        # Rule 2: Fast-Ice & Approach Advisory (Bharati / Prydz Bay Sector)
        # ------------------------------------------------------------------- #
        bharati_lat, bharati_lon = -69.407, 76.187
        try:
            w_bharati = environmental_data_provider.get_live_weather(
                bharati_lat, bharati_lon, timeout_s=2.5
            )
            b_is_live = bool(w_bharati.get("is_live", False))
            b_temp = w_bharati.get("temperature_2m_c")
            b_wind = w_bharati.get("wind_speed_knots")
            b_sic = w_bharati.get("sea_ice_concentration_pct")
            b_source = w_bharati.get("data_source", "Offline Metocean Store")
        except Exception as e:
            logger.warning("Failed to fetch weather for Bharati alert: %s", e)
            b_is_live = False
            b_temp = None
            b_wind = None
            b_sic = None
            b_source = "Offline Metocean Store (error fallback)"

        # Physical threshold evaluation: fire ONLY if sea-ice >= 15% (MIZ threshold),
        # freezing temperature <= -10°C, or winds >= 22 kts
        # Do NOT invent default numerical constants (no 18.0 kts or -12.0°C)
        b_threshold_met = (
            (b_sic is not None and b_sic >= 15.0) or
            (b_temp is not None and b_temp <= -10.0) or
            (b_wind is not None and b_wind >= 22.0)
        )

        if b_threshold_met:
            # Build conditional hazard explanation based strictly on which physical threshold fired
            triggers = []
            if b_sic is not None and b_sic >= 15.0:
                triggers.append(f"Sea-ice concentration ({b_sic:.1f}%) meets/exceeds 15% Marginal Ice Zone threshold")
            if b_temp is not None and b_temp <= -10.0:
                triggers.append(f"Sub-zero temperatures ({b_temp:.1f}°C) accelerate thermal freeze-up and grease/frazil ice formation")
            if b_wind is not None and b_wind >= 22.0:
                triggers.append(f"Coastal winds ({b_wind:.1f} kts) exceed 22 kt pack-compaction threshold")
            hazard_summary = "; ".join(triggers)

            if ((b_sic is not None and b_sic >= 50.0) or
                (b_wind is not None and b_wind >= 34.0) or
                (b_temp is not None and b_temp <= -20.0)):
                b_severity = "CRITICAL"
            elif (b_sic is not None and b_sic >= 15.0) or (b_wind is not None and b_wind >= 22.0):
                b_severity = "HIGH"
            else:
                b_severity = "WARNING"

            b_feed_tag = "Live metocean feed" if b_is_live else "Offline metocean reference store"
            b_temp_str = f"{b_temp:.1f}°C" if b_temp is not None else "no data"
            b_wind_str = f"{b_wind:.1f} kts" if b_wind is not None else "no data"
            b_sic_str = f"{b_sic:.1f}%" if b_sic is not None else "no data"

            alerts.append({
                "id": "ALERT-POLARIS-APPROACH-BHARATI",
                "timestamp": now_iso,
                "severity": b_severity,
                "source": "POLARIS Rule Engine (illustrative scenario alert, not an official bulletin)",
                "is_official_bulletin": False,
                "disclaimer": DISCLAIMER_TEXT,
                "title": f"FAST-ICE REGIME & APPROACH ADVISORY: BHARATI SECTOR ({b_severity})",
                "description": (
                    f"Prydz Bay approach (69°24'S, 76°11'E). {b_feed_tag}: "
                    f"Temp {b_temp_str}, Wind {b_wind_str}, Ice {b_sic_str} (Source: {b_source}). "
                    f"Triggered conditions: {hazard_summary}."
                ),
                "coordinates": {"lat": bharati_lat, "lon": bharati_lon},
                "recommended_action": (
                    "Comply with IMO Polar Code Chapter 9 (Safety of Navigation) and Chapter 11 "
                    "(Voyage Planning) operational guidelines: calculate daily vessel-specific "
                    "POLARIS Risk Index Outcome (RIO) before proceeding into ice regimes; "
                    "maintain dedicated bridge ice watch and adjust speed in pack-compaction zones."
                ),
                "is_live": b_is_live,
                "trigger_metrics": {
                    "wind_speed_knots": b_wind if b_wind is not None else "no data",
                    "temperature_c": b_temp if b_temp is not None else "no data",
                    "sea_ice_concentration_pct": b_sic if b_sic is not None else "no data",
                    "data_source": b_source,
                }
            })

        # ------------------------------------------------------------------- #
        # Rule 3: Iceberg Tracking & Distance-to-Route Leg Advisory
        # ------------------------------------------------------------------- #
        # Separate maritime navigation corridors (prevents overland interpolation)
        CORRIDOR_BHARATI = [
            (-33.918, 18.423),  # Port of Cape Town
            (-45.0, 35.0),      # Sub-Antarctic crossing
            (-55.0, 52.0),      # Polar Front
            (-62.0, 65.0),      # Marginal Ice Zone boundary
            (-67.45, 72.80),    # Vessel operating sector (MV Vasiliy Golovnin)
            (-69.407, 76.187),  # Bharati Station (Prydz Bay)
        ]
        CORRIDOR_MAITRI = [
            (-33.918, 18.423),  # Port of Cape Town
            (-45.0, 20.0),      # Sub-Antarctic crossing
            (-55.0, 15.0),      # Polar Front
            (-62.0, 12.0),      # Marginal Ice Zone boundary
            (-68.0, 11.8),      # Princess Astrid Coast approach
            (-70.767, 11.733),  # Maitri Station (Queen Maud Land)
        ]

        def _dist_to_corridor_legs(b_lat: float, b_lon: float, corridor: List[Tuple[float, float]], num_samples: int = 30) -> float:
            min_d = float("inf")
            for i in range(len(corridor) - 1):
                lat1, lon1 = corridor[i]
                lat2, lon2 = corridor[i + 1]
                dlon = (lon2 - lon1 + 180.0) % 360.0 - 180.0
                for s in range(num_samples + 1):
                    frac = s / float(num_samples)
                    p_lat = lat1 + frac * (lat2 - lat1)
                    p_lon = ((lon1 + frac * dlon + 180.0) % 360.0) - 180.0
                    d = _haversine_nm(b_lat, b_lon, p_lat, p_lon)
                    if d < min_d:
                        min_d = d
            return min_d

        all_bergs = iceberg_service.list_icebergs()
        fleet_vessels = vessel_service.list_vessels()

        if all_bergs:
            for berg in all_bergs:
                try:
                    b_lat = float(berg["lat"])
                    b_lon = float(berg["lon"])
                except (KeyvalueError, TypeError, ValueError):
                    continue

                d_bharati = _dist_to_corridor_legs(b_lat, b_lon, CORRIDOR_BHARATI)
                d_maitri = _dist_to_corridor_legs(b_lat, b_lon, CORRIDOR_MAITRI)
                min_corr_dist = min(d_bharati, d_maitri)
                corr_name = "Bharati Corridor" if d_bharati <= d_maitri else "Maitri Corridor"

                # Measure distance to dynamic live fleet vessel positions (not hard-coded)
                vessel_dists = []
                for v in fleet_vessels:
                    pos = v.get("current_position", {})
                    if "lat" in pos and "lon" in pos:
                        v_dist = _haversine_nm(b_lat, b_lon, float(pos["lat"]), float(pos["lon"]))
                        vessel_dists.append((v["name"], v_dist))

                closest_vessel_name, min_vessel_dist = (
                    min(vessel_dists, key=lambda x: x[1]) if vessel_dists else ("Fleet Vessel", 99999.0)
                )

                # Fire alert if within precautionary surveillance zone (<= 100 NM) of a route leg or vessel
                effective_hazard_dist = min(min_corr_dist, min_vessel_dist)
                if effective_hazard_dist <= 100.0:
                    berg_is_live = bool(berg.get("is_live"))
                    if berg_is_live:
                        tracking_note = (
                            f"Live satellite scatterometer fix (DOY {berg.get('observation_doy', 'no data')}, "
                            f"Source: {berg.get('surveillance_source', 'BYU/ASCAT')})."
                        )
                    else:
                        tracking_note = (
                            "Historical BYU/USNIC consolidated archive fix."
                            + (" Note: A-23a is not currently listed on the active BYU near-real-time scatterometer feed."
                               if berg.get("id") == "A-23a" else "")
                        )

                    area_val = berg.get("area_km2")
                    area_str = f"{area_val:,.0f} km²" if area_val is not None else "no data"
                    severity = "CRITICAL" if effective_hazard_dist <= 30.0 else "WARNING"

                    alerts.append({
                        "id": f"ALERT-POLARIS-BERG-{berg['id']}",
                        "timestamp": now_iso,
                        "severity": severity,
                        "source": "POLARIS Rule Engine (illustrative scenario alert, not an official bulletin)",
                        "is_official_bulletin": False,
                        "disclaimer": DISCLAIMER_TEXT,
                        "title": f"TABULAR ICEBERG ADVISORY: {berg['name'].upper()} ({severity})",
                        "description": (
                            f"Iceberg {berg['id']} ({area_str}) located at "
                            f"{abs(b_lat):.2f}°{'S' if b_lat < 0 else 'N'}, "
                            f"{abs(b_lon):.2f}°{'W' if b_lon < 0 else 'E'} — "
                            f"measured {min_corr_dist:.1f} NM from active {corr_name} leg and "
                            f"{min_vessel_dist:.1f} NM from {closest_vessel_name}. "
                            f"{tracking_note} Calved growlers and bergy bits possible within stand-off zone."
                        ),
                        "coordinates": {"lat": b_lat, "lon": b_lon},
                        "recommended_action": (
                            f"Comply with IMO Polar Code Chapter 9 (Safety of Navigation) and Chapter 11 "
                            f"(Voyage Planning): maintain minimum 30 NM standoff from detected tabular ice "
                            f"(current clearance: {effective_hazard_dist:.1f} NM); keep continuous forward radar "
                            f"watch and searchlight readiness in poor visibility."
                        ),
                        "is_live": berg_is_live,
                        "trigger_metrics": {
                            "iceberg_id": berg["id"],
                            "lat": b_lat,
                            "lon": b_lon,
                            "area_km2": area_val if area_val is not None else "no data",
                            "distance_to_route_nm": round(min_corr_dist, 1),
                            "distance_to_vessel_nm": round(min_vessel_dist, 1),
                            "standoff_threshold_nm": 30.0,
                            "is_live_track": berg_is_live
                        }
                    })

        self._cached_alerts = alerts
        self._last_refresh = now
        return alerts


alert_service = AlertService()
